# This is a basic workflow to help you get started with Actions

name: Postman API Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Install Node.js environment      
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
    # Install newman
      - name: Install newman
        run: |
           npm install -g newman
           npm install -g newman-reporter-html
           
      - name: Make Directory for results
        run: mkdir -p testResults
        
    # Run Postman Collection and output the file as html
      - name: Run Postman Collection
        run: |
          newman run ./tests/contactList.postman_collection.json -e ./tests/contactList.postman_environment.json -r cli,html --reporter-html-template "./reportingTheme/template-default-colored.hbs" --reporter-html-export testResults/testReport.html
          
    # Upload test results
      - name: Output the run details
        uses: actions/upload-artifact@v2
        with:
          name: RunReport
          path: testResults/testReport.html
          
    # Send Message to Slack Channel
      - name: Notify Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C01K4R1NFB7\",\"text\":\"Hello world\"}'
       
          
         
